blogger/urls.py
from django.urls import path
from . import views

app_name='blogger'
urlpatterns=[
	path('',views.IndexView.as_view(),name='index'),
	path('registeration/',views.registeration,name='registeration'),
	path('<int:pk>/',views.DetailView.as_view(),name='details'),
	path('login/',views.login,name='login'),
	path('logout/',views.logout,name='logout'),
	path('myblogs/',views.myblogs,name='myblogs'),
	path('addblog/',views.AddblogView.as_view(),name='addblog'),
	path('<int:pk>/edit/',views.UpdateBlogView.as_view(),name='editblog'),
	path('<int:pk>/delete/',views.DeleteBlogView.as_view(),name='deleteblog'),
	path('addcategory/',views.AddcategoryView.as_view(),name='addcategory'),
	path('category/<str:cats>/',views.CategoryView,name='category'),
	#path('search/<slug:query>/',views.search,name='search')
	]

myblog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
	path('blogger/',include('blogger.urls')),
    path('admin/', admin.site.urls),
]

blogger/models.py
from django.db import models
from django.urls import reverse
import django
from django.contrib.auth.models import User
from django.http import HttpResponse 

# Create your models here.
class Category(models.Model):
	name=models.CharField(max_length=250)
	
	def __str__(self):
		return self.name
	def get_absolute_url(self):
		return reverse('blogger:index')
 

class Blog(models.Model):
	
	blog_name=models.CharField(max_length=100)
	author=models.ForeignKey(User,on_delete=models.CASCADE,null="true")
	date=models.DateTimeField(default=django.utils.timezone.now())
	blog_text=models.TextField()
	category=models.CharField(max_length=250,default='uncategorized')

	def __str__(self):
		return self.blog_name

	def publish_date(self):
		return date
	def get_absolute_url(self):
		return reverse('blogger:index')

blogger/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User,auth
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Blog,Category

choices=Category.objects.all().values_list('name','name')
cats=[]
for i in choices:
	cats.append(i)

class CreateUserForm(UserCreationForm):
	"""docstring for CreateUserForm"""
	class Meta:
		model = User
		fields=['username','email','password1','password2']

class BlogForm(forms.ModelForm):
	class Meta:
		model=Blog
		fields=('blog_name','date','author','category','blog_text')
		
		widgets={
			'blog_name':forms.TextInput(attrs={'class':'form-control'}),
			'date':forms.DateTimeInput(attrs={'class':'form-control'}),
			'author':forms.Select(attrs={'class':'form-control'}),
			'category':forms.Select(choices=cats,attrs={'class':'form-control'}),
			'blog_text':forms.Textarea(attrs={'class':'form-control'})
		}

class UpdateBlogForm(forms.ModelForm):
	class Meta:
		model=Blog
		fields=('blog_name','date','category','blog_text')

		widgets={
			'blog_name':forms.TextInput(attrs={'class':'form-control'}),
			'date':forms.DateTimeInput(attrs={'class':'form-control'}),
			'category':forms.Select(choices=cats,attrs={'class':'form-control'}),
			'blog_text':forms.Textarea(attrs={'class':'form-control'})
		}

blogger/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from django.forms import inlineformset_factory
from django.urls import reverse,reverse_lazy
from django.views import generic
from .models import Blog, Category
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.models import User,auth
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm, BlogForm,UpdateBlogForm
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .filters import BlogFilter
# Create your views here.
	
"""def search(request):
    query = request.GET['query']
    if len(query)>78:
        allBlogs = Blogs.object.none()
    else:
        allBlogTitle = Blog.objects.filter(title__icontains=query)
        allBolgsContent = Blog.objects.filter(content__icontains=query)
        allBlogs = allBlogsTitle.union(allBlogsContent)
    if allBlogs.count == 0:
            messages.warning(request, "No search result found. please rechcek your input")
    params = {'allBlogs': allBlogs, 'query':query}
    return render(request, 'blogger/search.html',params)
"""
class IndexView(generic.ListView):
	template_name='blogger/index.html'
	model=Blog
	ordering=['-date']
	paginate_by=5

	def get_context_data(self,**kwargs):
		context=super().get_context_data(**kwargs)
		context['filter']=BlogFilter(self.request.GET,queryset=self.get_queryset())
		return context

	
class DetailView(generic.DetailView):
	model=Blog
	template_name='blogger/details.html'

def registeration(request):
	form=CreateUserForm()

	if request.method == 'POST':
		form=CreateUserForm(request.POST)
		if form.is_valid():
			form.save()
			user=form.cleaned_data.get('username')
			messages.success(request,'Congratulations! Account is created for ' + user)
			return redirect('/blogger/login')

	context={'form':form}
	return render(request,'blogger/registeration.html',context)
	
def login(request):

	if request.method=='POST':
		username=request.POST.get('username')
		password=request.POST.get('password')

		user=authenticate(request,username=username, password=password)

		if user is not None:
			auth_login(request,user)
			return redirect('/blogger')
		else:
			messages.info(request,"Username or password is incorrect")

	context={}
	return render(request,'blogger/login.html',context)

def CategoryView(request,cats):

	category_blogs=Blog.objects.filter(category=cats)
	return render(request,'blogger/categories.html',{'cats':cats,'category_posts':category_blogs})

@login_required(login_url='/blogger/login')
def logout(request):
	auth_logout(request)
	return redirect('/blogger/login')

@login_required(login_url='/blogger/login')
def myblogs(request):
	blogs=Blog.objects.filter(author=request.user).order_by('-date')
	context={'blogs':blogs}
	return render(request,'blogger/myblogs.html',context)
	
@method_decorator(login_required, name='dispatch')
class AddblogView(generic.CreateView):
	model = Blog
	form_class=BlogForm
	
	template_name = 'blogger/addblog.html'
	
	def get(self,request,*args,**kwargs):
		form=self.form_class(initial={'author':request.user})
		return render(request,self.template_name,{'form':form})

	def post(self,request,*args,**kwargs):
		form=self.form_class(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/blogger')
		return render(request,self.template_name,{'form':form})

@method_decorator(login_required, name='dispatch')
class AddcategoryView(generic.CreateView):
	model = Category
	fields='__all__'
	template_name = 'blogger/addcategory.html'

@method_decorator(login_required, name='dispatch')
class UpdateBlogView(generic.UpdateView):
	model=Blog
	form_class=UpdateBlogForm
	template_name='blogger/editblog.html'
	

@method_decorator(login_required, name='dispatch')
class DeleteBlogView(generic.DeleteView):
	model=Blog
	template_name='blogger/deleteblog.html'
	success_url=reverse_lazy('blogger:index')


"""
@method_decorator(login_required, name='dispatch')
class myblogsIndexView(generic.ListView):
	template_name='blogger/myblogs.html'
	context_object_name='users_latest_blog_list'
	paginate_by=5
	
	def get_username(request):
		username = Anonymous
		if request.user.is_authenticated():
			username= self.request.user
		return username
	
	def get_queryset(self):
		uname=get_username(request)
		return Blog.objects.filter(username=uname).order_by('-date')
"""

#registeration
"""if request.method == 'POST': 
		
		first_name = request.POST.get('firstName')
		last_name = request.POST.get('lastName')
		username = request.POST.get('userName')
		email = request.POST.get('inputEmail3')
		password=request.POST.get('inputPassword3')
		password1=request.POST.get('inputPassword4')
		if password1==password:
			if User.objects.filter(email = email).exists():
				messages.info(request,'Email Taken')
				return redirect('registeration')
			elif User.objects.filter(username=username).exists():
				messages.info(request,'Username Taken')
				return redirect('registeration')
			else:
				user = User.objects.create_user(username=username,password=password,email=email,first_name=first_name,last_name=last_name)
				user.save()
				print("user")
				return redirect('login')
		else:
			messages.info(request,"Password don't match!")
			return rediect('registeration')
	else:
		return render(request,'blogger/registeration.html')
"""

blogger/templates/blogger/addblog.html
{% extends "blogger/base.html" %}
{% block title %}Add Blog{% endblock %}
{% block content %}
<div class="card">
  <div class="card-header bg-warning">
    Add Blog
  </div>
  <div class="card-body">
<div class="form-group">
<form method="POST">
	<table>
	{% csrf_token %}
	{{ form.as_table}}
	</table>
</br>
	 <button type="submit" class="btn btn-primary">Post</button>
	 <a href="{% url 'blogger:index' %}" class="btn btn-dark">Cancel</a>
	</form>
</div>
  </div>
</div>
{% endblock %}

blogger/templates/blogger/addcategory.html
{% extends "blogger/base.html" %}
{% block title %}Add Blog Category{% endblock %}
{% block content %}
<div class="card">
  <div class="card-header bg-warning">
    Add Blog Category
  </div>
  <div class="card-body">
<div class="form-group">
<form method="POST">
	<table>
	{% csrf_token %}
	{{ form.as_table}}
	</table>
</br>
	 <button type="submit" class="btn btn-primary">Post</button>
	 <a href="{% url 'blogger:index' %}" class="btn btn-dark">Cancel</a>
	</form>
</div>
  </div>
</div>
{% endblock %}

blogger/templates/blogger/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Blogger{% endblock %}</title> <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
       
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'blogger:index' %}">Blogger</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        {% if not request.user.is_authenticated %}
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'blogger:registeration' %}">Register <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blogger:login'%}">Login</a>
      </li>
      {% endif %}
      {% if request.user.is_authenticated %}
      <li class="nav-item ">
        <a class="nav-link " href="{% url 'blogger:myblogs' %}">My Blogs</a>
      </li>
      
      <li class="nav-item ">
        <a class="nav-link " href="{% url 'blogger:logout' %}">Logout</a>
      </li>
      
     <li class="nav-item ">
        <a class="nav-link btn-dark" href="{% url 'blogger:addblog' %}">Add Blog</a>
      </li>&nbsp&nbsp&nbsp

      <li class="nav-item ">
        <a class="nav-link btn-success" href="{% url 'blogger:addcategory' %}">Add Blog Category</a>
      </li>
    </ul>

    <nav class="navbar navbar-success ">
  <span class="navbar-text bg-dark txt-warning">
    Welcome, {{request.user}}!
  </span>
</nav>
{% endif %}
    
  </div>
    </nav>

    {% block content %}

    {% endblock %}

    {% block footer %}

    <div class="footer">
        <div class="section-inner clearfix">
            <hr>
            <p>&copy;Blogger</p>
        </div>
    </div>

    {% endblock %}

</body>
</html>

blogger/templates/blogger/categories.html
{% extends "blogger/base.html"  %}

{% block content %}

<div class="jumbotron jumbotron-fluid bg-warning">
  <div class="container">
    <h1 class="display-4-danger">{{cats}}</h1>  
  </div>
</div>

{% if category_posts %}

	{% for blog in category_posts %}

		<div class="card-fluid border-danger mb-5 "style="border-color:red">
  			<h5 class="card-header bg-success">{{blog.blog_name}}</h5>
  			<div class="card-body">
    			<h6 class="card-subtitle mb-2 text-muted">Published on {{blog.date}} by {{blog.author}}</br>
    			Category : {{blog.category}}</h6>
    			<p class="card-text">{{blog.blog_text|safe}}</p>
    			<a href="{% url 'blogger:details' blog.id%}" class="btn btn-dark">Go to Blog</a>
  			</div>
		</div>
	{% endfor %}
	
{% else %}
	<p>No blogs are available.</p>
{% endif %}
{% if is_paginated %}
<nav aria-label="page navigation example">
	<ul class="pagination">
{% if page_obj.has_previous %}

		<li class="page-item " ><a class="page-link bg-dark " href="?page={{ page_obj.previous_page_number }}">« PREV</a></li>
{% endif %}

{% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active"><a class="page-link bg-danger" href="#">{{ i }}</a></li>
      {% else %}
        <li><a class="page-link bg-dark" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}

{% if page_obj.has_next %}
		<li class="page-item"><a class="page-link bg-dark" href="?page={{ page_obj.next_page_number }}">NEXT »</a>
		</li>
{% endif %}
</ul>
</nav>
{% endif %} 

{% endblock %}

blogger/templates/blogger/deleteblog.html
{% extends "blogger/base.html" %}
{% block title %}Delete Blog Confirmation{% endblock %}
{% block content %}
<div class="card">
  <div class="card-header bg-warning">
  <h3>Delete: {{blog.blog_name}}</h3>
  </div>
  <div class="card-body">
<h3>Are you sure?</h3>
<form method="POST">
	<table>
	{% csrf_token %}
	
	</table>
</br>
	 <button type="submit" class="btn btn-primary">Delete</button>
	 <a href="{% url 'blogger:details' pk=blog.id %}" class="btn btn-dark">Cancel</a>
	</form>

  </div>
</div>
{% endblock %}

blogger/templates/blogger/details.html
{% extends "blogger/details_base.html"  %}

{% block content %}
<div class="card">
  <h3 class="card-header bg-success">{{blog.blog_name}}</h3>
  <div class="card-body">
    <h6 class="card-subtitle mb-2 text-muted">Published on {{blog.date}} by {{blog.author}}</br> Category:{{blog.category}}</h6>
    <p class="card-text">{{blog.blog_text|safe}}</p>
    {% if request.user.is_authenticated and blog.author == request.user %}
    <a href="{% url 'blogger:editblog' pk=blog.pk %}" class="btn btn-dark">Edit</a>
    <a href="{% url 'blogger:deleteblog' pk=blog.pk %}" class="btn btn-dark">Delete</a>
    {% endif %}
    <a href="{% url 'blogger:index' %}" class="btn btn-dark">Go Back</a>
    
    
  </div>
</div>
{% endblock %}

blogger/templates/blogger/details_base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Blogger{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">        
</head>
<body>

      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'blogger:index' %}">Blogger</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        {% if request.user.is_authenticated == False %}
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'blogger:registeration' %}">Register <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blogger:login'%}">Login</a>
      </li>
      {% endif %}

      {% if request.user.is_authenticated %}
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'blogger:myblogs' %}">My Blogs</a>
      </li>
      
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'blogger:logout' %}">Logout</a>
      </li>


     <li class="nav-item ">
        <a class="nav-link btn-dark" href="{% url 'blogger:addblog' %}">Add Blog</a>
      </li>
      
      <li class="nav-item ">
        <a class="nav-link btn-dark" href="{% url 'blogger:addblog' %}">Add Blog Category</a>
      </li>

    </ul>

    <nav class="navbar navbar-success ">
  <span class="navbar-text bg-dark">
    Welcome, {{request.user}}!
  </span>
</nav>
{% endif %}
    
  </div>
    </nav>



    {% block content %}

    {% endblock %}

    {% block footer %}

    <div class="footer">
        <div class="section-inner clearfix">
           <hr>
            <p>&copy;Blogger</p>
        </div>
    </div>

    {% endblock %}

</body>
</html>

blogger/templates/blogger/editblog.html
{% extends "blogger/base.html" %}
{% block title %}Edit Blog{% endblock %}
{% block content %}
<div class="card">
  <div class="card-header bg-warning">
    Edit Blog
  </div>
  <div class="card-body">

<form method="POST">
	<table>
	{% csrf_token %}
	{{ form.as_table}}
	</table>
</br>
	 <button type="submit" class="btn btn-primary">Update</button>
	 <a href="{% url 'blogger:index' %}" class="btn btn-dark">Cancel</a>
	</form>

  </div>
</div>
{% endblock %}

blogger/templates/blogger/index.html
{% extends "blogger/base.html"  %}

{% block content %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4-danger">Welcome to Blogger!</h1>
    <p class="lead">This is a Blogsite with variety of knowledge and new things updated daily!</p>
  </div>
</div>
<h1><span class="badge badge-success">Latest Blogs are here</span></h1>



<div>
	<form method="GET">
{{ filter.form }}
	<button type="submit" class="btn btn-primary">Filter</button>
</form></div>




{% if object_list %}

	{% for blog in filter.qs %}


		<div class="card-fluid border-danger mb-5 "style="border-color:red">
  			<h5 class="card-header bg-warning">{{blog.blog_name}}</h5>
  			<div class="card-body">
    			<h6 class="card-subtitle mb-2 text-muted">Published on {{blog.date}} by {{blog.author}}</br>
    			Category : {{blog.category}}</h6>
    			<p class="card-text">{{blog.blog_text|safe}}</p>
    			<a href="{% url 'blogger:details' blog.id%}" class="btn btn-dark">Go to Blog</a>
  			</div>
		</div>
	{% endfor %}
	
{% else %}
	<p>No blogs are available.</p>
{% endif %}
{% if is_paginated %}
<nav aria-label="page navigation example">
	<ul class="pagination">
{% if page_obj.has_previous %}

		<li class="page-item " ><a class="page-link bg-dark " href="?page={{ page_obj.previous_page_number }}">« PREV</a></li>
{% endif %}

{% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active"><a class="page-link bg-danger" href="#">{{ i }}</a></li>
      {% else %}
        <li><a class="page-link bg-dark" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}

{% if page_obj.has_next %}
		<li class="page-item"><a class="page-link bg-dark" href="?page={{ page_obj.next_page_number }}">NEXT »</a>
		</li>
{% endif %}
</ul>
</nav>
{% endif %} 
 
{% endblock %}

blogger/templates/blogger/login.html
{% extends "blogger/base.html" %}
{% block content %}
<div class="card">
  <div class="card-header bg-warning">
    Log In
  </div>
  <div class="card-body">
<form action="{% url 'blogger:login' %}" method="POST">
  {% csrf_token %}
  <div class="form-group">
    <label for="exampleInputUsername">Username</label>
    <input type="text" class="form-control" name="username" id="username" aria-describedby="usernameHelp" placeholder="enter username">
      </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" name="password" class="form-control" id="password" placeholder="Password">
  </div>
  
  <button type="submit" class="btn btn-primary">Login</button>
</form>
</div>

{% for message in messages %}
      <p id= messages>{{message}}
{% endfor %}

<div class='nt-4'>
        <div class="d-flex justify-content-left links">
          Don't have an account?<a href="{% url 'blogger:registeration' %}" class="ml-2">register</a>
        </div>
      </div>
</div>
</div>

{% endblock %}

blogger/templates/blogger/myblogs.html
{% extends "blogger/base.html" %}
{% block content %}
<div class="jumbotron jumbotron-fluid bg-secondary">
  <div class="container">
    <h1 class="display-4-danger">Blogs of Mine!</h1>  
  </div>
</div>

{% if blogs %}

	{% for blog in blogs %}

		<div class="card-fluid border-danger mb-5 "style="border-color:red">
  			<h5 class="card-header bg-warning">{{blog.blog_name}}</h5>
  			<div class="card-body">
    			<h6 class="card-subtitle mb-2 text-muted">Published on {{blog.date}}</br>Category : {{blog.category}}  </h6>
    			<p class="card-text">{{blog.blog_text}}</p>
    			<a href="{% url 'blogger:details' blog.id%}" class="btn btn-dark">Go to Blog</a>
  			</div>
		</div>
	{% endfor %}
	
{% else %}
	<p>No blogs are available.</p>
{% endif %}
{% if is_paginated %}
<nav aria-label="page navigation example">
	<ul class="pagination">
{% if page_obj.has_previous %}

		<li class="page-item " ><a class="page-link bg-dark " href="?page={{ page_obj.previous_page_number }}">« PREV</a></li>
{% endif %}

{% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active"><a class="page-link bg-danger" href="#">{{ i }}</a></li>
      {% else %}
        <li><a class="page-link bg-dark" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}

{% if page_obj.has_next %}
		<li class="page-item"><a class="page-link bg-dark" href="?page={{ page_obj.next_page_number }}">NEXT »</a>
		</li>
{% endif %}
</ul>
</nav>
{% endif %} 

{% endblock %}

blogger/templates/blogger/registeration.html
{% extends "blogger/base.html"  %}
{% block content %}
<div class="card">
  <div class="card-header bg-warning">
    Registeration
  </div>
  <div class="card-body">
    <form action="" method="POST">
      {% csrf_token %}  
  
<div class="form-group row">
    <label for="userName"class="col-sm-2 col-form-label">Username</label>
    <div class="cpl-sm-10">
    {{form.username}}
  </div>
</div>
  <div class="form-group row">
    <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
    <div class="cpl-sm-10">
      {{form.email}}
    </div>
  </div>
  <div class="form-group row">
    <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label>
    <div class="cpl-sm-10">
      {{form.password1}}
    </div>
  </div>
  <div class="form-group row">
    <label for="inputPassword4" class="col-sm-2 col-form-label">Confirm Password</label>
    <div class="cpl-sm-10">
      {{form.password2}}
    </div>
  </div>

  <div class="form-group row">
    <div class="cpl-sm-10">
      <button type="submit" class="btn btn-primary">Sign in</button>
    </div>
  </div>
  {{form.errors}}
</form>
      <div class='nt-4'>
        <div class="d-flex justify-content-left links">
          Already have an account?<a href="{% url 'blogger:login' %}" class="ml-2">Login</a>
        </div>
      </div>

  </div>
  <script>

    var form_fields=document.getElementsbyTagName('input')
    form_fields[1].placeholder='Username..';
    from_feilds[2].placeholder='Email..';
    form_fields[3].placeholder='Enter Password';
    form_fields[4].placeholder='Confirm Password';

    for( var field in form_fields){
      form_fields[field].className += 'form-control'
    }
  </script>
{% endblock %}

blogger/templates/blogger/search.html
{% extends "blogger/base.html"  %}

{% block content %}


<h1><span class="badge badge-success">Latest Blogs are here</span></h1>
{% if allBlogs %}

	{% for blog in allBlogs %}

		<div class="card-fluid border-danger mb-5 "style="border-color:red">
  			<h5 class="card-header bg-warning">{{blog.blog_name}}</h5>
  			<div class="card-body">
    			<h6 class="card-subtitle mb-2 text-muted">Published on {{blog.date}} by {{blog.author}}</br>
    			Category : {{blog.category}}</h6>
    			<p class="card-text">{{blog.blog_text|safe}}</p>
    			<a href="{% url 'blogger:details' blog.id%}" class="btn btn-dark">Go to Blog</a>
  			</div>
		</div>
	{% endfor %}
	
{% else %}
	<p>No blogs are available.</p>
    {% for message in messages %}
      <p id= messages>{{message}}
{% endfor %}
{% endif %}



{% if is_paginated %}
<nav aria-label="page navigation example">
	<ul class="pagination">
{% if page_obj.has_previous %}

		<li class="page-item " ><a class="page-link bg-dark " href="?page={{ page_obj.previous_page_number }}">« PREV</a></li>
{% endif %}

{% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active"><a class="page-link bg-danger" href="#">{{ i }}</a></li>
      {% else %}
        <li><a class="page-link bg-dark" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}

{% if page_obj.has_next %}
		<li class="page-item"><a class="page-link bg-dark" href="?page={{ page_obj.next_page_number }}">NEXT »</a>
		</li>
{% endif %}
</ul>
</nav>
{% endif %} 

{% endblock %}